# Generated by Django 5.0.6 on 2024-07-27 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_mobile", message="手机号格式错误", regex="^1[3-9]\\d{9}$"
                    )
                ],
                verbose_name="手机号",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="phone_number",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_mobile", message="手机号格式错误", regex="^1[3-9]\\d{9}$"
                    )
                ],
                verbose_name="手机号",
            ),
        ),
    ]
