# Generated by Django 5.0.6 on 2024-07-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0003_teacher_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="level",
            field=models.SmallIntegerField(
                choices=[(1, "普通教师"), (2, "优秀教师"), (3, "特级教师")],
                default=1,
                verbose_name="级别",
            ),
        ),
    ]
