# Generated by Django 5.0.6 on 2024-07-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0004_alter_teacher_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="uid",
            field=models.IntegerField(default=11996, verbose_name="教师ID"),
        ),
    ]
