# Generated by Django 5.0.6 on 2024-07-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0005_alter_teacher_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="uid",
            field=models.IntegerField(verbose_name="教师ID"),
        ),
    ]
