# Generated by Django 5.0.6 on 2024-07-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0007_student_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="img",
            field=models.FileField(
                max_length=128, upload_to="StudentTx", verbose_name="头像"
            ),
        ),
    ]
