# Generated by Django 5.0.6 on 2024-07-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0008_alter_student_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="usertype",
            field=models.CharField(default="manager", max_length=12, verbose_name="类型"),
        ),
        migrations.AddField(
            model_name="student",
            name="usertype",
            field=models.CharField(default="student", max_length=12, verbose_name="类型"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="usertype",
            field=models.CharField(default="teacher", max_length=12, verbose_name="类型"),
        ),
    ]
